sonar.projectKey=geeklab_front
sonar.projectName=GeekLab Frontend
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,**/*.test.js,**/*.spec.js,dist/**
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.spec.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
